version: '3'

services:
  browserless:
    image: browserless/chrome:1.53-puppeteer-1.20.0
    hostname: browser
    init: true
    volumes:
      - "sessions:/sessions"
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      CONNECTION_TIMEOUT: -1
      KEEP_ALIVE: "true"
      WORKSPACE_EXPIRE_DAYS: 1
      CHROME_PATH: "/usr/bin/google-chrome"
      USE_CHROME_STABLE: "true"
      NODE_ENV: "production"
      ENABLE_XVBF: "true"
      MAX_CONCURRENT_SESSIONS: 100,
      QUEUE_LENGTH: 100,
      ENABLE_CORS: "true",
volumes:
  sessions:
